name: new_weather
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  

  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.0
  dio: ^4.0.6
  retrofit: ^3.3.1
  json_serializable: ^6.5.4
  retrofit_generator: ^4.2.0
  http: ^0.13.5
  riverpod: ^2.1.3
  flutter_riverpod: ^2.1.3
  provider: ^6.0.5
  dartz: ^0.10.1
  equatable: ^2.0.5
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  flutter_svg: ^1.1.6
  either_dart: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1

flutter:
  
    

  uses-material-design: true
  
  
  
  
  
  
  
